# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/saga/unzip-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/saga/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
    vendor/htc/saga/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/saga/proprietary/libv8.so:obj/lib/libv8.so \
    vendor/htc/saga/proprietary/libjni_latinime.so:obj/lib/libjni_latinime.so

# All the blobs necessary for saga
PRODUCT_COPY_FILES += \
    vendor/htc/saga/proprietary/awb_camera:/system/bin/awb_camera \
    vendor/htc/saga/proprietary/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/saga/proprietary/bcm4329.hcd:system/vendor/firmware/bcm4329.hcd \
    vendor/htc/saga/proprietary/default.acdb:system/etc/firmware/default.acdb \
    vendor/htc/saga/proprietary/default_org.acdb:system/etc/firmware/default_org.acdb \
    vendor/htc/saga/proprietary/default_org_wb.acdb:system/etc/firmware/default_org_wb.acdb \
    vendor/htc/saga/proprietary/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
    vendor/htc/saga/proprietary/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
    vendor/htc/saga/proprietary/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
    vendor/htc/saga/proprietary/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
    vendor/htc/saga/proprietary/vidc_720p_mp2_dec_mc.fw:system/etc/firmware/vidc_720p_mp2_dec_mc.fw \
    vendor/htc/saga/proprietary/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
    vendor/htc/saga/proprietary/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
    vendor/htc/saga/proprietary/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
    vendor/htc/saga/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/saga/proprietary/libposteffect.so:/system/lib/libposteffect.so
